In [16]:
import cv2
import random

Video 1

In [17]:
img = cv2.imread('assets/logo.jpg', 0)
img = cv2.resize(img, (0,0), fx=0.5, fy=0.5)
img = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)

-1 = original
1 = rgb
0 = grayscale

In [18]:
cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
cv2.imwrite('new_img.jpg', img)

True

In [20]:
img

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], shape=(500, 498), dtype=uint8)

Video 2

In [40]:
img = cv2.imread('assets/logo.jpg', -1)

In [34]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


Imagens são armazenadas em arrays do numpy

In [35]:
print(type(img))

<class 'numpy.ndarray'>


In [36]:
print(img.shape)

(995, 1000, 3)


Mudar parte da imagem

In [38]:
for i in range(100):
	for j in range(img.shape[1]):
		img[i][j] = [random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)]


In [42]:
cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Copiar parte da imagem

In [43]:
tag = img[500:700, 600:900]
img[100:300, 650:950] = tag

In [44]:
cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Video 3

In [3]:
import numpy as np
import cv2

In [9]:
cap = cv2.VideoCapture(0)
while True:
    ret, frame = cap.read()
    width = int(cap.get(3))
    height = int(cap.get(4))

    image = np.zeros(frame.shape, np.uint8)
    smaller_frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)

    image[:height//2,:width//2] = cv2.rotate(smaller_frame, cv2.ROTATE_180)
    image[height//2:,:width//2] = smaller_frame
    image[:height//2,width//2:] = cv2.rotate(smaller_frame, cv2.ROTATE_180)
    image[height//2:,width//2:] = smaller_frame
    

    cv2.imshow('frame', image)

    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

Video 4

In [1]:
import numpy as np
import cv2

In [12]:
cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)
while True:
    ret, frame = cap.read()
    width = int(cap.get(3))
    height = int(cap.get(4))
    
    img = cv2.line(frame, (0,0), (width, height), (255,0,0), 10)
    img = cv2.line(img, (0,height), (width, 0), (0,255,0), 5)
    img = cv2.rectangle(img, (100,100), (200,200), (128,128,128), 5)
    img = cv2.circle(img, (300,300), 60, (0,0,255), -1)
    font = cv2.FONT_HERSHEY_SIMPLEX
    img = cv2.putText(img, 'Tim is Great!', (10, height-10), font, 2, (0,0,0), 5, cv2.LINE_AA)

    cv2.imshow('frame', img)

    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

Video 5

In [1]:
import numpy as np
import cv2

In [56]:
cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)
while True:
    ret, frame = cap.read()
    width = int(cap.get(3))
    height = int(cap.get(4))

    
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    lower_blue = np.array([0,170,100])
    upper_blue = np.array([100,255,255])

    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    result = cv2.bitwise_and(frame, frame, mask=mask)

    cv2.imshow('frame', result)
    cv2.imshow('mask', mask)

    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [7]:
BGR_color = np.float32(np.array([[[255,0,0]]]))
x = cv2.cvtColor(BGR_color, cv2.COLOR_BGR2HSV)
x[0][0]

array([240.,   1., 255.], dtype=float32)

Video 6

In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('assets/chessboard.png')
img = cv2.resize(img, (0, 0), fx=0.75, fy=0.75)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [3]:
corners = cv2.goodFeaturesToTrack(gray, 100, 0.01, 10)
corners = np.intp(corners)

In [4]:
for corner in corners:
    x,y = corner.ravel()
    cv2.circle(img, (x,y), 5, (255,0,0), -1)

In [5]:
for i in range(len(corners)):
	for j in range(i + 1, len(corners)):
		corner1 = tuple(corners[i][0])
		corner2 = tuple(corners[j][0])
		color = tuple(map(lambda x: int(x), np.random.randint(0, 255, size=3)))
		cv2.line(img, corner1, corner2, color, 1)


In [7]:
cv2.imshow('Frame', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Video 7

In [8]:
import numpy as np
import cv2

In [14]:
img = cv2.imread('assets/soccer_practice.jpg', 0)
template = cv2.imread('assets/shoe.PNG', 0)
h, w = template.shape

In [10]:
methods = [cv2.TM_CCOEFF, cv2.TM_CCOEFF_NORMED, cv2.TM_CCORR,
            cv2.TM_CCORR_NORMED, cv2.TM_SQDIFF, cv2.TM_SQDIFF_NORMED]

In [15]:
for method in methods:
    img2 = img.copy()

    result = cv2.matchTemplate(img2,template,method)
    min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)
    if method in [cv2.TM_SQDIFF, cv2.TM_SQDIFF_NORMED]:
        location = min_loc
    else:
        location = max_loc

    bottom_right = (location[0] + w, location[1] + h)
    cv2.rectangle(img2, location, bottom_right, 255, 5)
    cv2.imshow('Match', img2)
    cv2.waitKey(0)
    cv2.destroyAllWindows()